@startuml Use Case Diagram

left to right direction

actor "Library User" as user
actor "Library Administrator" as admin

rectangle "LibraryApp System" {
    usecase "Borrow Book" as UC_BORROW
    usecase "Return Book" as UC_RETURN
    usecase "Manage Books" as UC_MANAGE_BOOKS
    usecase "Manage Authors" as UC_MANAGE_AUTHORS
    usecase "Manage Publishers" as UC_MANAGE_PUBLISHERS
    usecase "Manage Categories" as UC_MANAGE_CATEGORIES
    usecase "Manage Users" as UC_MANAGE_USERS
    usecase "Search Books" as UC_SEARCH
    usecase "View Book Details" as UC_VIEW_DETAILS
    usecase "Manage Profile" as UC_MANAGE_PROFILE
}

user -- UC_BORROW
user -- UC_RETURN
user -- UC_SEARCH
user -- UC_VIEW_DETAILS
user -- UC_MANAGE_PROFILE

admin -- UC_MANAGE_BOOKS
admin -- UC_MANAGE_AUTHORS
admin -- UC_MANAGE_PUBLISHERS
admin -- UC_MANAGE_CATEGORIES
admin -- UC_MANAGE_USERS

@enduml
