name: Deploy API to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/Presentation/LibraryApp.API/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Dotnet info
        run: dotnet --info

      - name: Restore
        run: dotnet restore backend/Presentation/LibraryApp.API/LibraryApp.API.csproj

      - name: Build
        run: dotnet build backend/Presentation/LibraryApp.API/LibraryApp.API.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish backend/Presentation/LibraryApp.API/LibraryApp.API.csproj -c Release -o out --no-build

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "LibraryApp"   # örn: libraryapp-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: out
