name: Build and deploy ASP.Net Core app to Azure Web App - LibraryApp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Proje YOLU: csproj SENDE burada
      - name: Restore
        run: dotnet restore backend/Presentation/LibraryApp.API/LibraryApp.API.csproj

      - name: Build
        run: dotnet build backend/Presentation/LibraryApp.API/LibraryApp.API.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish backend/Presentation/LibraryApp.API/LibraryApp.API.csproj -c Release -o app --no-build

      # Publish çıktısını "app/" klasörü olarak artifact'a koyuyoruz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      # Artifact'ı "app/" klasörüne indir
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_366264F6E94A4E33BE14B6220B55DCD6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1EA5B205703E4A87A36A09A253199A11 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6AE3B82B4817452E843388B703900B57 }}

      # "package" artık app/ klasörü (dosyalar burada)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LibraryApp'   # App Service adın
          slot-name: 'Production'
          package: app
